import { Leaf, Store as StoreIcon, Zap } from 'lucide-react';
import { CategoryID, Store, Language } from './types';

export const TRANSLATIONS: Record<Language, any> = {
  fr: {
    welcome: "Tout ce que vous voulez, livré vite.",
    getStarted: "Commencer",
    home: "Accueil",
    favorites: "Favoris",
    noFavorites: "Vous n'avez pas encore de favoris.",
    addToFavorite: "Ajouter aux favoris",
    orders: "Commandes",
    profile: "Profil",
    guest: "Utilisateur",
    deliverTo: "Livrer à",
    searchPlaceholder: "Rechercher...",
    services: "Nos Services",
    popular: "Populaires à proximité",
    viewAll: "Tout voir",
    allStores: "Tous les magasins",
    newStores: "Nouveaux Magasins",
    seeMore: "Voir plus",
    showLess: "Voir moins",
    settings: "Paramètres",
    language: "Langue",
    logout: "Déconnexion",
    help: "Aide & Support",
    notifications: "Notifications",
    payments: "Paiements",
    privacy: "Confidentialité",
    edit: "Modifier",
    orderAgain: "Commander à nouveau",
    totalOrders: "total",
    myOrders: "Mes Commandes",
    trackOrder: "Suivre ma livraison",
    Gallery: "Galerie",
    // Login & Signup
    welcomeBack: "Bon retour ! 👋",
    enterEmailToContinue: "Entrez votre email pour continuer.",
    enterPhoneToContinue: "Entrez votre numéro pour continuer.",
    phone: "Téléphone",
    email: "Email",
    loading: "Chargement...",
    optional: "Optionnel",
    loginRequired: "Veuillez vous connecter pour continuer.",
    continueAsGuest: "Continuer en tant qu'invité",
    password: "Mot de passe",
    passwordTooShort: "Le mot de passe doit contenir au moins 6 caractères",
    forgotPassword: "Mot de passe oublié ?",
    login: "Se connecter",
    loginTimeout:
      "Délai dépassé lors de la connexion. Vérifiez votre connexion Internet puis réessayez.",
    loginUnexpectedError: "Connexion impossible pour le moment. Verifiez la connexion puis reessayez.",
    noAccount: "Vous n'avez pas de compte ?",
    signup: "S'inscrire",
    skipLoginDev: "Skip Login (Dev Only)",
    welcomeSignup: "Bienvenue ! ✨",
    createAccount: "Créez votre compte pour commencer.",
    fullName: "Nom Complet",
    fullNamePlaceholder: "Ex: Ahmed Benali",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    phoneError9Digits: "Le numéro doit contenir 9 chiffres après +212",
    enterFullName: "Veuillez entrer votre nom complet",
    createMyAccount: "Créer mon compte",
    // CategoryDetail
    establishments: "Établissements",
    expressService: "Express",
    ourCouriersHandleEverything: "Nos coursiers dédiés s'occupent de tout pour vous.",
    orderNow: "Commander ",
    open: "Ouvert",
    popularStore: "Populaire",
    delivery: "LIVRAISON",
    // Checkout
    requestingLocation: "Demande de localisation...",
    locationRequired: "📍 Position requise",
    allowLocation: "Activez votre localisation pour pouvoir livrer votre commande.",
    allowLocationBtn: "Autoriser la localisation",
    activateLocation: "Activer la localisation",
    orderSummary: "Résumé de commande",
    cart: "Panier",
    textOrder: "Commande texte",
    prescription: "Ordonnance",
    yourOrder: "Votre commande",
    productTotal: "Total produits",
    deliveryFee: "Frais de livraison",
    total: "Total",
    paymentMethod: "Mode de paiement",
    cashOnDelivery: "Espèces à la livraison",
    bankTransfer: "Virement bancaire",
    selectBank: "Choisir une banque",
    uploadReceipt: "Téléverser le reçu",
    tapToUpload: "Appuyez pour téléverser",
    changeReceipt: "Changer le reçu",
    confirmOrder: "Confirmer la commande",
    pleaseFillAll: "Veuillez remplir tous les champs requis",
    // Checkout - Additional
    finalize: "Finaliser",
    address: "Adresse",
    positionCaptured: "Position GPS capturée",
    positionRequired: "Position requise",
    precisionRequired: "Précision nécessaire pour le livreur.",
    cash: "Cash",
    transfer: "Virement",
    bank: "BANQUE",
    back: "Retour",
    proofRequired: "Preuve obligatoire",
    receiptRequired: "L'upload du reçu est obligatoire pour le virement.",
    selectReceipt: "Sélectionner Reçu",
    confirm: "Confirmer",
    geolocationNotSupported: "La géolocalisation n'est pas supportée.",
    notAvailableInYourCity: "Service disponible uniquement à Kénitra pour le moment.",
    permissionDenied: "Permission refusée.",
    pleaseUploadReceipt: "Veuillez uploader votre reçu bancaire.",
    errorUploadingImages: "Erreur lors de l'envoi des images. Réessayez.",
    confirmTimeout: "La requête a pris trop de temps. Réessayez.",
    ribCopied: "RIB Copié !",
    copyFailed: "Copie impossible",
    orderProducts: "Produits de la commande",
    cartEmpty: "Votre panier est vide",
    cartEmptyHint: "Ajoutez des articles à votre panier pour continuer",
    nameCopied: "Nom Copié !",
    selectTransferToSeeRib: "Choisir « Virement » pour afficher les RIB.",
    noRibsAvailable: "Aucun RIB configuré. Contactez le support.",
    ribsLoadError: "Impossible de charger les RIB.",
    ribsRLSHint: "Dans Supabase : Table ribs → RLS → Autoriser SELECT (policy « Allow public read »).",
    // Category names
    food: "Gastronomie",
    pharmacie: "Pharmacie",
    boulangerie: "Boulangerie",
    pressing: "Pressing",
    legumes: "Légumes",
    market: "Market",
    yourBudget: "Votre Budget Total  que tu as consommé ",
    totalAmount: "Montant Total",
    priceOnRequest: "Sur devis",
    enterPrice: "Saisissez le prix",
    // Store views
    popularStores: "Magasins Populaires",
    viewStore: "Voir le magasin",
    select: "Sélectionner",
    orderByTyping: "Commandez en tapant votre demande personnalisée",
    uploadPrescription: "Veuillez uploader votre ordonnance et nous nous chargerons du reste",
    express: "Express",
    // Home view
    allProducts: "Tous les produits",
    collapse: "Réduire",
    buy: "Acheter",
    scrollToSeeAll: "Scrollez pour voir tout",
    // Profile Edit
    enterEmail: "Entrez votre email",
    save: "Enregistrer",
    saving: "Enregistrement...",
    saved: "Profil mis à jour avec succès !",
    cancel: "Annuler",
    name: "Nom",
    enterName: "Entrez votre nom complet",
    enterPhone: "Entrez votre téléphone",
    nameRequired: "Le nom est requis",
    phoneRequired: "Le téléphone est requis",
    invalidEmail: "Format d'email invalide",
    emailAlreadyExists: "Cet email est déjà utilisé",
    // Permissions
    permissionsRequired: "Autorisations requises",
    permissionsMessage: "Pour une expérience optimale, nous avons besoin de quelques accès.",
    skipPermissions: "Passer",
    locationPermission: "Localisation",
    locationDesc: "Pour trouver les livreurs proches.",
    callsPermission: "Appels",
    callsDesc: "Pour contacter votre livreur.",
    contactsPermission: "Contacts",
    contactsDesc: "Pour partager l'app avec vos amis.",
    authorize: "AUTORISER",
    continueToApp: "Continuer vers l'app",
    ignoreForNow: "Ignorer pour le moment",
    // Help & Support
    helpSupport: "Aide & Support",
    agentOnline: "Agent en ligne",
    emergency: "Une urgence ?",
    agentsAvailable: "Nos agents sont disponibles 24/7 pour vous assister dans vos livraisons.",
    startLiveChat: "Lancer le chat en direct",
    commonQuestions: "Questions fréquentes",
    callLabel: "Appeler",
    emailLabel: "Email",
    mailUs: "Nous écrire",
    faqOrderWhereAnswer: "Ouvrez la section `Commandes` depuis le menu pour voir l’état de votre livraison. Si votre commande n’apparaît pas, contactez notre support pour vérification.",
    faqOrderColdAnswer: "Désolé pour l’incident. Contactez notre support dès que possible (téléphone ou email) et indiquez le numéro de commande afin que nous puissions vous aider rapidement.",
    faqPaymentProblemAnswer: "Si le paiement échoue, réessayez plus tard ou changez de méthode de paiement. Pour une aide immédiate, contactez notre support en indiquant l’heure et le montant de la commande.",
    faqChangeAddressAnswer: "Pour modifier l’adresse, contactez notre support le plus tôt possible afin que nous puissions traiter la demande avant expédition.",
    // Tracking View
    trackingTitle: "Suivi de la commande",
    noActiveOrder: "Aucune commande en cours",
    backToHome: "Retour à l'accueil",
    pending: "En attente de validation",
    accepted: "Commande acceptée",
    preparing: "En préparation",
    delivering: "En livraison",
    delivered: "Livrée",
    en_attente: "En attente",
    en_verification: "En vérification",
    en_traitement: "En traitement",
    en_course: "En course",
    en_progression: "En progression",
    indisponible: "Indisponible",
    refusee: "Refusée",
    livree: "Livrée",
    deliveryStatus: "Status de livraison",
    support: "Support",
    chatWithDriver: "Chat",
    customOrder: "Commande personnalisée",
    startOrder: "Commencer la commande",
    // Email Verification
    verifyEmail: "Vérifiez votre email",
    verifyEmailMessage: "Nous avons envoyé un lien de vérification à votre adresse email. Veuillez cliquer sur le lien pour activer votre compte.",
    checkSpamFolder: "Vérifiez votre dossier spam/courrier indésirable",
    goToLogin: "Aller à la connexion",
    didntReceiveEmail: "Vous n'avez pas reçu l'email ?",
    waitFewMinutes: "Attendez quelques minutes",
    checkEmailTypo: "Vérifiez qu'il n'y a pas de faute de frappe dans votre email",
    emailVerified: "Email vérifié !",
    emailVerifiedMessage: "Votre adresse email a été vérifiée avec succès. Vous pouvez maintenant vous connecter.",
    continueToLogin: "Continuer vers la connexion",
    accountReady: "Votre compte est maintenant prêt à être utilisé",
    emailResent: "Email renvoyé avec succès !",
    sending: "Envoi en cours...",
    resendEmail: "Renvoyer l'email",
    resendCode: "Renvoyer le code",
    verify: "Vérifier",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    passwordsDoNotMatch: "Les mots de passe ne correspondent pas",
    resetPassword: "Réinitialiser le mot de passe",
    enterCodeSentTo: "Entrez le code envoyé à",
    invalidCode: "Code invalide ou expiré",
    code6Digits: "Le code doit contenir 6 chiffres",
    tooManyRequests: "Trop de tentatives. Veuillez attendre.",
    // History View
    myOrdersHistory: "Mes Commandes",
    activeOrders: "En cours",
    pastOrders: "Historique",
    noOrders: "Aucune commande",
    startOrdering: "Commencez à commander pour voir votre historique ici.",
    orderNumber: "Commande",
    orderOn: "Commandé le",
    trackDelivery: "Suivre",
    reorder: "Recommander",
    statusDelivered: "LIVRÉE",
    statusRefused: "REFUSÉE",
    statusInProgress: "EN COURS",
    // Confirmation View
    orderConfirmed: "C'est parti !",
    orderConfirmedMsg: "Votre commande",
    isConfirmed: "est confirmée. Préparez-vous à déguster !",
    trackMyDelivery: "Suivre ma livraison",
    yourOpinionMatters: "Votre avis compte",
    rateRestaurant: "Notez le restaurant",
    rateDriver: "Notez le livreur",
    rateDelivery: "Notez la livraison",
    deliveryRatingPrompt: "Comment a été votre expérience sur l'application ?",
    submitRating: "Envoyer mon avis",
    thankYouRating: "Merci pour votre retour",
    ratingReceived: "Votre avis nous aide à améliorer le service.",
    ribSecurityMessage: "Paiement 100% sécurisé. En cas de problème, nous pouvons vous rembourser instantanément.",
    adminValidationMessage: "Votre commande sera traitée par l'administration pour validation.",
    backHome: "Retour à l'accueil",
    // New Translations
    min: "min",
    dh: "DH",
    success: "Succès",
    error: "Erreur",
    profileUpdated: "Profil mis à jour avec succès !",
    ratingSaved: "Votre avis a été enregistré.",
    orderError: "La commande n'a pas pu être enregistrée sur le serveur.",
    detecting: "Détection en cours...",
    useMyLocation: "Utiliser ma position",
    locationTimeout: "Délai dépassé. Réessayez ou choisissez sur la carte.",
    locationDeniedHelp: "Cliquez sur l’icône à gauche de l’adresse du site → Paramètres du site → Autoriser la localisation.",
    defaultLocation: "Localisation par défaut",
    unavailable: "Indisponible",
    stores: "Magasins",
    products: "Produits",
    noResults: "Aucun résultat",
    tryAnotherSearch: "Essayez une autre recherche",
    searchScanning: "Recherche dans le catalogue…",
    customOrderDescription: "Écrivez ici tous les produits depuis le menu et indiquez le prix total dans la case.",
    writeOrderPlaceholder: "Décrivez votre commande ici...",
    addImage: "Ajouter une photo",
    freeDelivery: "Livraison Gratuite",
    onFirstOrder: "Sur votre première commande Food",
    pharmacy247: "Pharmacie 24/7",
    medsIn15: "Vos médicaments en 15 min",
    bakeryPromo: "Promo Boulangerie",
    bakeryDiscount: "-20% sur les viennoiseries",
    deliveringTo: "Livrer à",
    pharmacyPlaceholder: "Listez vos médicaments ici...",
    addedToCart: "Ajouté au panier !",
    continueShopping: "Continuer les achats",
    offlineTitle: "Oups ! Vous êtes hors ligne",
    offlineMessage: "Vérifiez votre connexion pour continuer vos commandes.",
    retry: "Réessayer",
    catalogSlowLoadHint: "Le chargement est plus long que prévu. Vérifiez votre connexion puis réessayez.",
    noStoresYet: "Aucun magasin à afficher pour le moment.",
  },
  ar: {
    allStores: "جميع المتاجر",
    seeMore: "عرض المزيد",
    showLess: "عرض أقل",
    welcome: "كل ما تريده، يصلك بسرعة.",
    getStarted: "ابدأ الآن",
    home: "الرئيسية",
    favorites: "المفضلة",
    noFavorites: "لم تضف أي متجر للمفضلة بعد.",
    addToFavorite: "إضافة إلى المفضلة",
    orders: "طلباتي",
    profile: "الحساب",
    guest: "مستخدم",
    deliverTo: "التوصيل إلى",
    searchPlaceholder: "Search....",
    services: "خدماتنا",
    popular: "الأكثر شعبية بالقرب منك",
    viewAll: "عرض الكل",
    settings: "الإعدادات",
    language: "اللغة",
    logout: "تسجيل الخروج",
    help: "المساعدة والدعم",
    notifications: "التنبيهات",
    payments: "المدفوعات",
    privacy: "الخصوصية",
    edit: "تعديل",
    orderAgain: "إعادة الطلب",
    totalOrders: "المجموع",
    myOrders: "طلباتي السابقة",
    trackOrder: "تتبع طلبي",
    Gallery: "معرض الصور",
    // Login & Signup
    welcomeBack: "أهلاً بعودتك ! 👋",
    enterEmailToContinue: "أدخل بريدك الإلكتروني للمتابعة.",
    enterPhoneToContinue: "أدخل رقمك للمتابعة.",
    loading: "جاري التحميل...",
    optional: "اختياري",
    loginRequired: "يرجى تسجيل الدخول للمتابعة.",
    continueAsGuest: "تصفح كزائر",
    phone: "الهاتف",
    password: "كلمة المرور",
    passwordTooShort: "يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل",
    forgotPassword: "نسيت كلمة المرور ؟",
    login: "تسجيل الدخول",
    loginTimeout: "انتهت مهلة تسجيل الدخول. تحقق من اتصال الإنترنت ثم أعد المحاولة.",
    loginUnexpectedError: "تعذر تسجيل الدخول. أعد المحاولة.",
    noAccount: "ليس لديك حساب ؟",
    signup: "إنشاء حساب",
    skipLoginDev: "تخطي تسجيل الدخول (للمطورين)",
    welcomeSignup: "مرحباً ! ✨",
    createAccount: "أنشئ حسابك للبدء.",
    fullName: "الاسم الكامل",
    fullNamePlaceholder: "مثال: أحمد بنعلي",
    alreadyHaveAccount: "لديك حساب بالفعل ؟",
    phoneError9Digits: "يجب أن يحتوي الرقم على 9 أرقام بعد 212+",
    createMyAccount: "إنشاء حسابي",
    // CategoryDetail
    establishments: "المؤسسات",
    expressService: "سريع",
    ourCouriersHandleEverything: "سيتولى مندوبونا كل شيء من أجلك.",
    orderNow: "اطلب الآن",
    open: "مفتوح",
    popularStore: "شائع",
    delivery: "التوصيل",
    // Checkout
    requestingLocation: "طلب الموقع...",
    locationRequired: "📍 الموقع مطلوب",
    allowLocation: "قم بتفعيل موقعك لنتمكن من توصيل طلبك.",
    allowLocationBtn: "السماح بالموقع",
    activateLocation: "تفعيل الموقع",
    orderSummary: "ملخص الطلب",
    cart: "السلة",
    textOrder: "طلب نصي",
    prescription: "الوصفة الطبية",
    yourOrder: "طلبك",
    productTotal: "مجموع المنتجات",
    deliveryFee: "رسوم التوصيل",
    total: "المجموع",
    paymentMethod: "طريقة الدفع",
    cashOnDelivery: "الدفع عند الاستلام",
    bankTransfer: "تحويل بنكي",
    selectBank: "اختر البنك",
    uploadReceipt: "رفع الإيصال",
    tapToUpload: "اضغط للرفع",
    changeReceipt: "تغيير الإيصال",
    confirmOrder: "تأكيد الطلب",
    pleaseFillAll: "يرجى ملء جميع الحقول المطلوبة",
    // Checkout - Additional
    finalize: "إنهاء",
    address: "العنوان",
    positionCaptured: "تم التقاط موقع GPS",
    positionRequired: "الموقع مطلوب",
    precisionRequired: "دقة ضرورية للموصل.",
    cash: "نقدًا",
    transfer: "تحويل",
    bank: "البنك",
    back: "رجوع",
    proofRequired: "الدليل إلزامي",
    receiptRequired: "رفع الإيصال إلزامي للتحويل.",
    selectReceipt: "اختر الإيصال",
    confirm: "تأكيد",
    geolocationNotSupported: "تحديد الموقع غير مدعوم.",
    notAvailableInYourCity: "الخدمة متوفرة فقط في القنيطرة حالياً.",
    permissionDenied: "تم رفض الإذن.",
    pleaseUploadReceipt: "يرجى رفع إيصالك البنكي.",
    errorUploadingImages: "خطأ في إرسال الصور. حاول مرة أخرى.",
    confirmTimeout: "استغرق الطلب وقتاً طويلاً. حاول مرة أخرى.",
    ribCopied: "تم نسخ RIB !",
    copyFailed: "تعذر النسخ",
    orderProducts: "منتجات الطلب",
    cartEmpty: "سلتك فارغة",
    cartEmptyHint: "أضف عناصر إلى سلتك للمتابعة",
    nameCopied: "تم نسخ الاسم !",
    selectTransferToSeeRib: "اختر « تحويل » لعرض بيانات RIB.",
    noRibsAvailable: "لا يوجد RIB. اتصل بالدعم.",
    ribsLoadError: "تعذر تحميل RIB.",
    ribsRLSHint: "في Supabase: جدول ribs → RLS → اسمح بـ SELECT.",
    // Category names
    food: "الطعام",
    pharmacie: "صيدلية",
    boulangerie: "مخبز",
    pressing: "ملابس",
    legumes: "خضروات",
    market: "سوق",
    express: "سريع",
    newStores: "المتاجر الجديدة",
    yourBudget: "ميزانيتك / السعر (درهم)",
    totalAmount: "المبلغ الإجمالي",
    priceOnRequest: "حسب الطلب",
    enterPrice: "أدخل السعر",
    // Store views
    popularStores: "المتاجر الشائعة",
    viewStore: "عرض المتجر",
    select: "اختيار",
    orderByTyping: "اطلب بكتابة طلبك المخصص",
    uploadPrescription: "يرجى تحميل وصفتك الطبية وسنتولى الباقي",
    // Home view
    allProducts: "جميع المنتجات",
    collapse: "إخفاء",
    buy: "شراء",
    scrollToSeeAll: "مرر لرؤية الكل",
    // Profile Edit
    email: "البريد الإلكتروني",
    enterEmail: "أدخل بريدك الإلكتروني",
    save: "حفظ",
    saving: "جاري الحفظ...",
    saved: "تم تحديث الملف الشخصي بنجاح !",
    cancel: "إلغاء",
    name: "الاسم",
    enterName: "أدخل اسمك الكامل",
    enterPhone: "أدخل هاتفك",
    nameRequired: "الاسم مطلوب",
    phoneRequired: "الهاتف مطلوب",
    invalidEmail: "صيغة بريد إلكتروني غير صحيحة",
    emailAlreadyExists: "هذا البريد الإلكتروني مستخدم بالفعل",
    // Permissions
    permissionsRequired: "الأذونات المطلوبة",
    permissionsMessage: "للحصول على تجربة مثالية، نحتاج إلى بعض الوصول.",
    skipPermissions: "تخطي",
    locationPermission: "الموقع",
    locationDesc: "للعثور على السائقين القريبين.",
    callsPermission: "المكالمات",
    callsDesc: "للاتصال بسائقك.",
    contactsPermission: "جهات الاتصال",
    contactsDesc: "لمشاركة التطبيق مع أصدقائك.",
    authorize: "السماح",
    continueToApp: "متابعة إلى التطبيق",
    ignoreForNow: "تجاهل الآن",    // Help & Support
    helpSupport: "المساعدة والدعم",
    agentOnline: "الوكيل متصل",
    emergency: "حالة طارئة؟",
    agentsAvailable: "وكلاؤنا متاحون على مدار الساعة طوال أيام الأسبوع لمساعدتك في التوصيل.",
    startLiveChat: "بدء الدردشة المباشرة",
    commonQuestions: "الأسئلة الشائعة",
    callLabel: "اتصال",
    emailLabel: "بريد إلكتروني",
    mailUs: "راسلنا",
    faqOrderWhereAnswer: "افتح قسم `الطلبات` من القائمة لمعرفة حالة التوصيل. إذا لم تظهر طلبك، تواصل مع الدعم للتحقق.",
    faqOrderColdAnswer: "نعتذر عن الإزعاج. تواصل مع دعمنا في أقرب وقت (اتصال أو بريد إلكتروني) وأرسل رقم الطلب حتى نتمكن من مساعدتك بسرعة.",
    faqPaymentProblemAnswer: "إذا فشل الدفع، حاول مرة أخرى لاحقًا أو غيّر طريقة الدفع. للمساعدة السريعة، تواصل معنا مع وقت الطلب والمبلغ.",
    faqChangeAddressAnswer: "لتغيير العنوان، تواصل مع دعمنا بأسرع وقت ممكن حتى نتمكن من معالجة الطلب قبل الشحن.",
    // Tracking View
    trackingTitle: "تتبع الطلب",
    noActiveOrder: "لا توجد طلبات نشطة",
    backToHome: "العودة للرئيسية",
    pending: "في انتظار التأكيد",
    accepted: "تم قبول الطلب",
    preparing: "قيد التحضير",
    delivering: "قيد التوصيل",
    delivered: "تم التوصيل",
    en_attente: "قيد الانتظار",
    en_verification: "قيد التحقق",
    en_traitement: "قيد المعالجة",
    en_course: "في الطريق",
    en_progression: "قيد التقدم",
    indisponible: "غير متاح",
    refusee: "مرفوض",
    livree: "تم التوصيل",
    deliveryStatus: "حالة التوصيل",
    support: "الدعم",
    chatWithDriver: "دردشة",
    customOrder: "طلب خاص",
    startOrder: "بدء الطلب",
    // Email Verification
    verifyEmail: "تحقق من بريدك الإلكتروني",
    verifyEmailMessage: "لقد أرسلنا رابط التحقق إلى عنوان بريدك الإلكتروني. يرجى النقر على الرابط لتفعيل حسابك.",
    checkSpamFolder: "تحقق من مجلد الرسائل العشوائية",
    goToLogin: "انتقل إلى تسجيل الدخول",
    didntReceiveEmail: "لم تستلم البريد الإلكتروني؟",
    waitFewMinutes: "انتظر بضع دقائق",
    checkEmailTypo: "تأكد من عدم وجود أخطاء في عنوان بريدك",
    emailVerified: "تم التحقق من البريد الإلكتروني!",
    emailVerifiedMessage: "تم التحقق من عنوان بريدك الإلكتروني بنجاح. يمكنك الآن تسجيل الدخول.",
    continueToLogin: "الاستمرار لتسجيل الدخول",
    accountReady: "حسابك جاهز الآن للاستخدام",
    emailResent: "تم إعادة إرسال البريد بنجاح !",
    sending: "جاري الإرسال...",
    resendEmail: "إعادة إرسال البريد",
    resendCode: "إعادة إرسال الرمز",
    verify: "تحقق",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    passwordsDoNotMatch: "كلمات المرور غير متطابقة",
    resetPassword: "إعادة تعيين كلمة المرور",
    enterCodeSentTo: "أدخل الرمز المرسل إلى",
    invalidCode: "رمز غير صالح أو منتهي",
    code6Digits: "يجب أن يتكون الرمز من 6 أرقام",
    tooManyRequests: "طلبات كثيرة جداً. يرجى الانتظار.",
    // History View
    myOrdersHistory: "طلباتي",
    activeOrders: "نشطة",
    pastOrders: "السابقة",
    noOrders: "لا توجد طلبات",
    startOrdering: "ابدأ بالطلب لترى سجلك هنا.",
    orderNumber: "طلب",
    orderOn: "تم الطلب في",
    trackDelivery: "تتبع",
    reorder: "إعادة الطلب",
    statusDelivered: "تم التوصيل",
    statusRefused: "مرفوض",
    statusInProgress: "قيد التنفيذ",
    // Confirmation View
    orderConfirmed: "تم التأكيد!",
    orderConfirmedMsg: "طلبك",
    isConfirmed: "تم تأكيده. استعد للاستمتاع!",
    trackMyDelivery: "تتبع التوصيل",
    yourOpinionMatters: "رأيك مهم",
    rateRestaurant: "قيم المطعم",
    rateDriver: "قيم السائق",
    rateDelivery: "قيم التوصيل",
    deliveryRatingPrompt: "كيف كانت تجربة التطبيق؟",
    submitRating: "إرسال التقييم",
    thankYouRating: "شكراً لتقييمك",
    ratingReceived: "تقييمك يساعدنا على تحسين الخدمة.",
    ribSecurityMessage: "دفع آمن 100٪. في حالة حدوث مشكلة، يمكننا إعادة أموالك فوراً.",
    adminValidationMessage: "سيتم معالجة طلبك من قبل الإدارة للتحقق.",
    backHome: "العودة للرئيسية",
    // New Translations
    min: "دقيقة",
    dh: "درهم",
    success: "تم بنجاح",
    error: "خطأ",
    profileUpdated: "تم تحديث الملف الشخصي بنجاح!",
    ratingSaved: "تم حفظ تقييمك.",
    orderError: "لم يتم حفظ الطلب على الخادم.",
    detecting: "جاري تحديد الموقع...",
    useMyLocation: "استخدام موقعي",
    locationTimeout: "انتهت المهلة. أعد المحاولة أو اختر على الخريطة.",
    locationDeniedHelp: "من أيقونة القفل أو (i) بجانب العنوان ← إعدادات الموقع ← السماح بالموقع.",
    defaultLocation: "الموقع الافتراضي",
    unavailable: "غير متاح",
    stores: "المتاجر",
    products: "المنتجات",
    noResults: "لم يتم العثور على نتائج",
    tryAnotherSearch: "حاول البحث عن شيء آخر",
    searchScanning: "جاري البحث في المتجر…",
    customOrderDescription: "هذا المتجر لا يعرض منتجات محددة. يمكنك طلب ما تريد عن طريق وصف الطلب أو رفع صورة.",
    writeOrderPlaceholder: "اكتب تفاصيل طلبك هنا...",
    addImage: "إضافة صورة",
    freeDelivery: "توصيل مجاني",
    onFirstOrder: "على طلبك الأول",
    pharmacy247: "صيدلية 24/7",
    medsIn15: "أدويتك في 15 دقيقة",
    bakeryPromo: "عروض المخبزة",
    bakeryDiscount: "-20% على الحلويات",
    deliveringTo: "التوصيل إلى",
    pharmacyPlaceholder: "اكتب أسماء الأدوية هنا...",
    addedToCart: "تمت الإضافة إلى السلة!",
    viewCart: "عرض السلة",
    continueShopping: "مواصلة التسوق",
    offlineTitle: "عذراً! أنت غير متصل بالإنترنت",
    offlineMessage: "يرجى التحقق من اتصالك بالإنترنت للمتابعة",
    retry: "إعادة المحاولة",
    catalogSlowLoadHint: "التحميل يستغرق وقتاً أطول من المعتاد. تحقق من الاتصال ثم أعد المحاولة.",
    noStoresYet: "لا توجد متاجر للعرض حالياً.",
  },
  en: {
    welcome: "Everything you want, delivered fast.",
    getStarted: "Get Started",
    home: "Home",
    favorites: "Favorites",
    noFavorites: "You haven't added any favorites yet.",
    addToFavorite: "Add to favorites",
    orders: "Orders",
    profile: "Profile",
    guest: "User",
    deliverTo: "Deliver to",
    searchPlaceholder: "Search....",
    services: "Our Services",
    popular: "Popular nearby",
    viewAll: "View all",
    allStores: "All stores",
    seeMore: "See more",
    showLess: "Show less",
    settings: "Settings",
    language: "Language",
    logout: "Logout",
    help: "Help & Support",
    notifications: "Notifications",
    payments: "Payments",
    privacy: "Privacy",
    edit: "Edit",
    orderAgain: "Order Again",
    totalOrders: "total",
    myOrders: "My Orders",
    trackOrder: "Track my order",
    Gallery: "Gallery",
    // Login & Signup
    welcomeBack: "Welcome back! 👋",
    enterEmailToContinue: "Enter your email to continue.",
    enterPhoneToContinue: "Enter your number to continue.",
    loading: "Loading...",
    optional: "Optional",
    loginRequired: "Please login to continue.",
    continueAsGuest: "Continue as guest",
    phone: "Phone",
    password: "Password",
    passwordTooShort: "Password must be at least 6 characters",
    forgotPassword: "Forgot password?",
    login: "Login",
    loginTimeout: "Login timed out. Check your internet connection and try again.",
    loginUnexpectedError: "Could not sign in. Please try again.",
    noAccount: "Don't have an account?",
    signup: "Sign up",
    skipLoginDev: "Skip Login (Dev Only)",
    welcomeSignup: "Welcome! ✨",
    createAccount: "Create your account to get started.",
    fullName: "Full Name",
    fullNamePlaceholder: "Ex: Ahmed Benali",
    alreadyHaveAccount: "Already have an account?",
    phoneError9Digits: "Phone number must contain 9 digits after +212",
    enterFullName: "Please enter your full name",
    createMyAccount: "Create my account",
    // CategoryDetail
    establishments: "Establishments",
    expressService: "Express",
    ourCouriersHandleEverything: "Our dedicated couriers handle everything for you.",
    orderNow: "Order now",
    open: "Open",
    popularStore: "Popular",
    delivery: "DELIVERY",
    // Checkout
    requestingLocation: "Requesting location...",
    locationRequired: "📍 Position required",
    allowLocation: "Enable your location to deliver your order.",
    allowLocationBtn: "Allow location",
    activateLocation: "Activate Location",
    orderSummary: "Order Summary",
    cart: "Cart",
    textOrder: "Text order",
    prescription: "Prescription",
    yourOrder: "Your order",
    productTotal: "Product total",
    deliveryFee: "Delivery fee",
    total: "Total",
    paymentMethod: "Payment method",
    cashOnDelivery: "Cash on delivery",
    bankTransfer: "Bank transfer",
    selectBank: "Choose a bank",
    uploadReceipt: "Upload receipt",
    tapToUpload: "Tap to upload",
    changeReceipt: "Change receipt",
    confirmOrder: "Confirm order",
    pleaseFillAll: "Please fill all required fields",
    // Checkout - Additional
    finalize: "Finalize",
    address: "Address",
    positionCaptured: "GPS position captured",
    positionRequired: "Position required",
    precisionRequired: "Accuracy needed for delivery.",
    cash: "Cash",
    transfer: "Transfer",
    bank: "BANK",
    back: "Back",
    proofRequired: "Proof required",
    receiptRequired: "Receipt upload is mandatory for transfer.",
    selectReceipt: "Select Receipt",
    confirm: "Confirm",
    geolocationNotSupported: "Geolocation is not supported.",
    notAvailableInYourCity: "Service only available in Kenitra for the moment.",
    permissionDenied: "Permission denied.",
    pleaseUploadReceipt: "Please upload your bank receipt.",
    errorUploadingImages: "Error uploading images. Try again.",
    confirmTimeout: "Request took too long. Please try again.",
    ribCopied: "RIB Copied!",
    copyFailed: "Copy failed",
    orderProducts: "Order products",
    cartEmpty: "Your cart is empty",
    cartEmptyHint: "Add items to your cart to continue",
    nameCopied: "Name Copied!",
    selectTransferToSeeRib: "Select « Transfer » to see bank details (RIB).",
    noRibsAvailable: "No RIB configured. Contact support.",
    ribsLoadError: "Could not load RIBs.",
    ribsRLSHint: "In Supabase: ribs table → RLS → Allow SELECT (policy « Allow public read »).",
    // Category names
    food: "Food",
    pharmacie: "Pharmacy",
    boulangerie: "Bakery",
    pressing: "Laundry",
    legumes: "Vegetables",
    market: "Market",
    express: "Express",
    newStores: "New Stores",
    yourBudget: "Your Budget / Price (DH)",
    totalAmount: "Total Amount",
    priceOnRequest: "On request",
    enterPrice: "Enter price",
    // Store views
    popularStores: "Popular Stores",
    viewStore: "View Store",
    select: "Select",
    orderByTyping: "Order by typing your custom request",
    uploadPrescription: "Please upload your prescription and we'll take care of the rest",
    // Home view
    allProducts: "All products",
    collapse: "Collapse",
    buy: "Buy",
    scrollToSeeAll: "Scroll to see all",
    // Profile Edit
    email: "Email",
    enterEmail: "Enter your email",
    save: "Save",
    saving: "Saving...",
    saved: "Profile updated successfully!",
    cancel: "Cancel",
    name: "Name",
    enterName: "Enter your full name",
    enterPhone: "Enter your phone",
    nameRequired: "Name is required",
    phoneRequired: "Phone is required",
    invalidEmail: "Invalid email format",
    emailAlreadyExists: "This email is already in use",
    // Permissions
    permissionsRequired: "Permissions Required",
    permissionsMessage: "For an optimal experience, we need a few access permissions.",
    skipPermissions: "Skip",
    locationPermission: "Location",
    locationDesc: "To find nearby drivers.",
    callsPermission: "Calls",
    callsDesc: "To contact your driver.",
    contactsPermission: "Contacts",
    contactsDesc: "To share the app with your friends.",
    authorize: "AUTHORIZE",
    continueToApp: "Continue to app",
    ignoreForNow: "Ignore for now",
    // Help & Support
    helpSupport: "Help & Support",
    agentOnline: "Agent online",
    emergency: "An emergency?",
    agentsAvailable: "Our agents are available 24/7 to assist you with your deliveries.",
    startLiveChat: "Start live chat",
    commonQuestions: "Common questions",
    callLabel: "Call",
    emailLabel: "Email",
    mailUs: "Mail us",
    faqOrderWhereAnswer: "Open the `Orders` section from the menu to see your delivery status. If your order doesn’t show up, contact support for verification.",
    faqOrderColdAnswer: "Sorry about that. Contact support as soon as possible (phone or email) and include your order number so we can help quickly.",
    faqPaymentProblemAnswer: "If payment fails, try again later or switch payment method. For immediate help, contact support with the order time and amount.",
    faqChangeAddressAnswer: "To change your delivery address, contact support as early as possible so we can process the request before dispatch.",
    // Tracking View
    trackingTitle: "Order Tracking",
    noActiveOrder: "No active orders",
    backToHome: "Back to home",
    pending: "Awaiting validation",
    accepted: "Order accepted",
    preparing: "Preparing",
    delivering: "Delivering",
    delivered: "Delivered",
    en_attente: "Waiting",
    en_verification: "In verification",
    en_traitement: "Processing",
    en_course: "On the way",
    en_progression: "In progress",
    indisponible: "Unavailable",
    refusee: "Refused",
    livree: "Delivered",
    deliveryStatus: "Delivery status",
    support: "Support",
    chatWithDriver: "Chat",
    // Email Verification
    verifyEmail: "Verify your email",
    verifyEmailMessage: "We've sent a verification link to your email address. Please click on the link to activate your account.",
    checkSpamFolder: "Check your spam/junk folder",
    goToLogin: "Go to login",
    didntReceiveEmail: "Didn't receive the email?",
    waitFewMinutes: "Wait a few minutes",
    checkEmailTypo: "Check for typos in your email address",
    emailVerified: "Email verified!",
    emailVerifiedMessage: "Your email address has been successfully verified. You can now log in.",
    continueToLogin: "Continue to login",
    accountReady: "Your account is now ready to use",    // History View
    emailResent: "Email resent successfully!",
    sending: "Sending...",
    resendEmail: "Resend Email",
    resendCode: "Resend code",
    verify: "Verify",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    passwordsDoNotMatch: "Passwords do not match",
    resetPassword: "Reset password",
    enterCodeSentTo: "Enter the code sent to",
    invalidCode: "Invalid or expired code",
    code6Digits: "Code must be 6 digits",
    tooManyRequests: "Too many requests. Please wait.",
    myOrdersHistory: "My Orders",
    activeOrders: "Active",
    pastOrders: "Past",
    noOrders: "No orders",
    startOrdering: "Start ordering to see your history here.",
    orderNumber: "Order",
    orderOn: "Ordered on",
    trackDelivery: "Track",
    reorder: "Reorder",
    statusDelivered: "DELIVERED",
    statusRefused: "REFUSED",
    statusInProgress: "IN PROGRESS",
    // Confirmation View
    orderConfirmed: "All set!",
    orderConfirmedMsg: "Your order",
    isConfirmed: "is confirmed. Get ready to enjoy!",
    trackMyDelivery: "Track my delivery",
    yourOpinionMatters: "Your opinion matters",
    rateRestaurant: "Rate the restaurant",
    rateDriver: "Rate the driver",
    rateDelivery: "Rate the delivery",
    deliveryRatingPrompt: "How was your app experience?",
    submitRating: "Submit rating",
    thankYouRating: "Thank you for your feedback",
    ratingReceived: "Your feedback helps us improve the service.",
    ribSecurityMessage: "100% secure payment. We can refund you instantly if there is an issue.",
    adminValidationMessage: "Your order will be processed by administration for validation.",
    backHome: "Back to home",
    // New Translations
    min: "min",
    dh: "DH",
    success: "Success",
    error: "Error",
    profileUpdated: "Profile updated successfully!",
    ratingSaved: "Your rating has been saved.",
    orderError: "Order could not be saved to server.",
    detecting: "Detecting...",
    useMyLocation: "Use my location",
    locationTimeout: "Timed out. Try again or pick a point on the map.",
    locationDeniedHelp: "Click the lock or site icon in the address bar → Site settings → Allow location.",
    defaultLocation: "Default location",
    unavailable: "Unavailable",
    stores: "Stores",
    products: "Products",
    noResults: "No results found",
    tryAnotherSearch: "Try another search",
    searchScanning: "Searching the catalog…",
    customOrderDescription: "This store does not display specific products. You can order what you want by describing your order or uploading a photo.",
    writeOrderPlaceholder: "Describe your order here...",
    addImage: "Add photo",
    freeDelivery: "Free Delivery",
    onFirstOrder: "On your first Food order",
    pharmacy247: "Pharmacy 24/7",
    medsIn15: "Your meds in 15 min",
    bakeryPromo: "Bakery Promo",
    bakeryDiscount: "-20% on pastries",
    deliveringTo: "Deliver to",
    pharmacyPlaceholder: "List your medicines here...",
    addedToCart: "Added to cart!",
    viewCart: "View Cart",
    continueShopping: "Continue Shopping",
    offlineTitle: "Oops! You're Offline",
    offlineMessage: "Please check your internet connection to continue ordering.",
    retry: "Retry",
    catalogSlowLoadHint: "Loading is taking longer than expected. Check your connection and try again.",
    noStoresYet: "No stores to show right now.",
  },
};

// Icon mapping for categories (icons can't be stored in database)
export const CATEGORY_ICONS: Record<string, any> = {
  'food': '/food-icon.png',
  'pharmacie': '/pharmacy-icon.png',
  'boulangerie': '/Boulangerie-icon.png',
  'pressing': '/clothing-icon.png',
  'legumes': <Leaf className="w-8 h-8" />,
  'market': <StoreIcon className="w-8 h-8" />,
  'express': <Zap className="w-8 h-8" />,
};

// Default colors as fallback
export const CATEGORY_COLORS: Record<string, string> = {
  'food': 'bg-orange-500',
  'pharmacie': 'bg-emerald-600',
  'boulangerie': 'bg-amber-600',
  'pressing': 'bg-blue-500',
  'legumes': 'bg-green-600',
  'market': 'bg-purple-500',
  'express': 'bg-red-500',
};

// RIBS are now fetched from the database. Use getRibs() from ribService.ts
